---
title: "D3_Jeong,wonryeol"
author: "Jeong, wonryeol"
date:  "`r Sys.Date()`"
output: 
   pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    toc: yes
    toc_depth: 2
  



---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
#py_install("scipy")
```




\newpage
## Exercise 1
**How would you generalize this game with arbitrary value of $m_1$ (minimum increment), $m_2$ (maximum increment), and $N$ (the winning number)? **


\begin{itemize}
\item $S=\{1,2,3,4....N\}$
\item $A=\{a_{m1},a_{m1}+1,a_{m1}+2,a_{m1}+3,...a_{m2}\}$
\item $a_{m} =$ "increment by m 
\item $S_{next} = S_{now}+a_{now}$
\end{itemize}

\newpage
## Exercise 2
**Two players are to play a game. The two players take turns to call out integers. The rules are as follows. Describe A’s winning strategy.**

\begin{itemize}
\item A must call out an integer between 4 and 8, inclusive.
\item B must call out a number by adding A’s last number and an integer between 5 and 9, inclusive.
\item A must call out a number by adding B’s last number and an integer between 2 and 6, inclusive.
\item Keep playing until the number larger than or equal to 100 is called by the winner of this game.
\end{itemize}

To get optimal starategy, we should analysis number 

B can add at least 5 and at most 9 and A can add at least 2, at most 6

it means if one step is gone, at least 7 is increased and at most 15 is increased

For winning A, A should find out one step increasing. that is 11










\newpage
## Exercise 3
**There is only finite number of deterministic stationary policy. How many is it?**

\
\vspace{30pt}

Answer is $|A|^{|S|}$


\newpage
## Exercise 4
**Formulate the first example in this lecture note using the terminology including state, action, reward, policy, transition. \\ Describe the optimal policy using the terminology as well.**



A and B are to play a game. They take turn to call out integers. \\
1. The serving player must call out an integer between 1 or 2. \\
2. The opponent player 1) takes the other player’s number and 2) increments it by 1 or 2, then 3) call out the number. \\
3. Keep playing back and forth until someone calling out the number 31. The person calling out 31 is winner. 
    }%
}

\vspace{30pt}

\begin{itemize}
\item State = $1\le S_{t} \le 31 $
\item $a_{1}$ is increased by 1
\item $a_{2}$ is increased by 2
\end{itemize}


\begin{center}
Policy
\end{center}
******

if $S_{t}$ % 3 == 1:
  $a_{2}$
elif $S_{t}$ % 3 == 2:
  $a_{1}$
else:
\indent you loose



\begin{center}
Reward
\end{center}
******


\begin{itemize}
\item $R(29,a_{1})$ = 1
\item $R(28,a_{1})$ = 1
\item otherwise 0
\end{itemize}


\begin{center}
Transition
\end{center}
******

$P_{ss'}^a = P(S_{t+1} = S' \mid S_t = s, A_t = a) =1$  




\newpage
## Exercise 5
**From the first example**
\begin{itemize}
\item Assume that your opponent increments by 1 with prob 0.5 and by 2 with prob 0.5
\item Assume that the winning number is 0 instead of 31
\item your opponent played first and she called out 1
\item your current a policy $\pi_{0}$ is that
\begin{itemize}
\item if the current state s \le 5 then increment by 2
\item if the current state s > 5 then increment by 1
\end{itemize}
\end{itemize}

**Evaluate $V^{\pi_{0}}(1)$ **

$S_{1} = 1$

while $S_{t} \le 10$


\quad P = random Prob

\quad if P > 0.5 

\qquad $S_{t}=S_{t}+1$

\quad elif P \le 0.5

\qquad $S_{t}=S_{t}+2$

\quad If $S_{t}==10$ # when you lose


\qquad return 0

\quad If $S_{t}\le 5$

\qquad $S_{t+1}=S_{t}+2$

\quad If $S_{t} > 5$

\qquad $S_{t+1}=S_{t}+1$

\quad If $S_{t}$ == 10 # when you win

\qquad return 1


