---
title: "A6_Exercises"  
author: "Kwon do yun"  
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: True   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)

matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage


## implementation basic (P. 4)
```{python}
import numpy as np
np.random.seed(1234)
MC_N = 10**3
x = np.random.uniform(0,1,MC_N)*2-1
y = np.random.uniform(0,1,MC_N)*2-1
t = np.sqrt(x**2+y**2)
pi_hat = 4*sum(t<=1)/MC_N
print(pi_hat)
```

## implementation for (P. 5)
```{python}
import numpy as np
np.random.seed(1234)
MC_N = 10**6
count = 0
for MC_i in range(MC_N):
    x_i = np.random.uniform(0, 1) * 2 - 1
    y_i = np.random.uniform(0, 1) * 2 - 1
    t_i = np.sqrt(x_i**2+y_i**2)
    if t_i <=1:
        count = count+1
pi_hat = 4*count/MC_N
print(pi_hat)
```

## implementation time (P. 9)
```{python}
import numpy as np
from time import time
np.random.seed(1234)
beg_time = time()
old_est = 0
n = 1
MC_N = 10**6
while True:
    x_i = np.random.uniform(0, 1) * 2 - 1
    y_i = np.random.uniform(0, 1) * 2 - 1
    t_i = np.sqrt(x_i**2+y_i**2)
    A_n = 4*(t_i<=1)
    new_est = ((n-1)/n)*old_est + (1/n)*A_n
    if(n>MC_N):
        break
    n = n+1
    old_est = new_est
end_time = time()
print(new_est)
print('Time difference of ',end_time-beg_time, 'secs')
```

## Convergence trajectory

```{python}
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1234)
old_est = 0
n = 1
MC_N = 10**6
results = np.repeat(0,MC_N+1).astype('float')
while True:
    x_i = np.random.uniform(0, 1) * 2 - 1
    y_i = np.random.uniform(0, 1) * 2 - 1
    t_i = np.sqrt(x_i**2+y_i**2)
    A_n = 4*(t_i<=1)
    new_est = ((n-1)/n)*old_est + (1/n)*A_n
    results[n] = new_est
    if(n>=MC_N):
        break
    n = n+1
    old_est = new_est
```
```{python}
plt.plot(results[1:21],marker='o')
plt.xlabel('Index')
plt.ylabel('results[0:20]')
plt.xticks([5,10,15,20])
plt.show()
```

```{python}
plt.plot(results[1001:1021],marker='o')
plt.xlabel('Index')
plt.ylabel('results[1000:1020]')
plt.xticks([5,10,15,20])
plt.show()
```

```{python}
plt.plot(results[100000:100021],marker='o')
plt.xlabel('Index')
plt.ylabel('results[100000:100020]')
plt.xticks([5,10,15,20])
plt.show()
```


```{r, results='hide'}
"A6_Exercises"
```