---
title: "A6_손민상"
author: "Son Min Sang"  
date:  "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
     in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
py_install("pandas")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage
## page 4
```{python, echo=TRUE}
import numpy as np

np.random.seed(1234) # fix the random seed
MC_N = 10**3
x= np.random.uniform(0,1,MC_N)*2-1 # runif() generates U(0,1)
y= np.random.uniform(0,1,MC_N)*2-1
t = np.sqrt(x**2 +y**2)
pi_hat=4*sum(t<=1)/MC_N
pi_hat
```

## page 5

```{python, echo=TRUE}
import numpy as np

np.random.seed(1234)
MC_N = 10**6
count = 0 
for MC_i in range(MC_N):
    x_i= np.random.uniform(0,1,1)*2-1
    y_i= np.random.uniform(0,1,1)*2-1
    t_i = np.sqrt(x_i**2+y_i**2)
    if t_i <= 1:
        count +=1
    
pi_hat=4*count/MC_N
pi_hat
```


\newpage

## page 9

```{python, echo=TRUE}
import numpy as np
import time

np.random.seed(1234)
beg_time = time.time()
old_est = 0 
n = 1
MC_N = 10**6
old_est = 0
while True:
    x_i= np.random.uniform(0,1,1)*2-1
    y_i= np.random.uniform(0,1,1)*2-1
    t_i = np.sqrt(np.power(x_i,2) +np.power(y_i,2))
    A_n = 4*(t_i<=1)
    new_est = ((n-1)/n)*old_est + (1/n)*A_n
    if n>MC_N :
        break
    n = n+1
    old_est = new_est
    
print(new_est)
```

```{python, echo=TRUE}
import time

end_time = time.time()
print("Time difference of ",(end_time-beg_time),'sec')
```


\newpage
## page 10

```{python, echo=TRUE}
import numpy as np

np.random.seed(1234)
beg_time = time.time() # to time
old_est = 0 
n = 1
MC_N = 10**6
old_est = 0
results = np.zeros(MC_N+1)
count = 0 
while True:
    x_i= np.random.uniform(0,1,1)*2-1
    y_i= np.random.uniform(0,1,1)*2-1
    t_i = np.sqrt(np.power(x_i,2) +np.power(y_i,2))
    A_n = 4*(t_i<=1)
    new_est = ((n-1)/n)*old_est + (1/n)*A_n
    results[count] = new_est # to save
    if n>MC_N :
        break
    n +=1
    count +=1
    old_est = new_est
```

\newpage

```{python, echo=TRUE}
import matplotlib.pyplot as plt

plt.plot(results[:21],marker='o')
plt.rcParams['figure.figsize'] =(10,10)
plt.xlabel('Index')
plt.ylabel('results[0:21]')
plt.xticks([5,10,15,20])
plt.show()
```

\newpage

## page 11
```{python, echo=TRUE}
import matplotlib.pyplot as plt

plt.plot(results[1000:1021],marker='o')
plt.xlabel('Index')
plt.ylabel('results[1000:1020]')
plt.xticks([5,10,15,20])
plt.show()
```

\newpage


```{python, echo=TRUE}
import matplotlib.pyplot as plt

plt.plot(results[100000:100021],marker='o')
plt.xlabel('Index')
plt.ylabel('results[100000:100020]')
plt.xticks([5,10,15,20])
plt.show()
```