---
title: "A6 Python ver"
author: "Lee SungHo"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
py_install("matplotlib")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage
## page 4 Implementation-basic
```{python, echo=TRUE}
import numpy as np

np.random.seed(1234) # fix the random seed
N = 10**3
x = np.random.rand(N,1)*2 - 1 
y = np.random.rand(N,1)*2 - 1
t = np.sqrt(x**2+y**2) 

pi_hat = 4*np.sum(t<=1) / N
pi_hat
```


\newpage
## page 5 "The first-time would write"
```{python, echo=TRUE}

np.random.seed(1234) # fix the random seed

MC_N = 10**6
count = 0

for MC_i in range(MC_N):
  x_i = np.random.uniform(0,1)*2 - 1 
  y_i = np.random.uniform(0,1)*2 - 1
  t_i = np.sqrt(x_i**2+y_i**2) 
  
  if t_i <= 1:
    count= count + 1
 
pi_hat = 4*count / MC_N
pi_hat
```


\newpage
## page 10 convergence trajectory
```{python, echo=TRUE}
import time 

np.random.seed(1234) # fix the random seed
beg_time = time.time()
old_est = 0
n = 1
MC_N = 10**6


while True:
    x_i=np.random.uniform(0,1)*2-1
    y_i=np.random.uniform(0,1)*2-1
    t_i=np.sqrt(x_i**2+y_i**2)
    
    A_n=4*(t_i<=1)
    
    new_est=((n-1)/n)*old_est + (1/n)*A_n
    
    if n > MC_N:
        break
    
    n+=1
    old_est=new_est
    
print(new_est)

end_time=time.time()
print('Time difference of ',end_time-beg_time,' secs')
```


\newpage
### page 10 convergence trajectory
```{python, echo=TRUE}
import matplotlib.pyplot as plt

np.random.seed(1234) # fix the random seed
beg_time = time.time()
old_est = 0
n = 1
MC_N = 10**6
results = []


while True:
    x_i=np.random.uniform(0,1)*2-1
    y_i=np.random.uniform(0,1)*2-1
    t_i=np.sqrt(x_i**2+y_i**2)
    
    A_n=4*(t_i<=1)
    
    new_est=((n-1)/n)*old_est + (1/n)*A_n
    results.append(new_est)
    
    if n > MC_N:
        break
    
    n+=1
    old_est=new_est
    
plt.plot(results[0:20],marker='o')
plt.xlabel('Index')
plt.ylabel('results[0:20]')
plt.xticks([5,10,15,20])
plt.show()
```

## page 10 Graph
```{python, echo=TRUE}
    
plt.plot(results[1000:1020],marker='o')
plt.xlabel('Index')
plt.ylabel('results[1000:1020]')
plt.xticks([5,10,15,20])
plt.show()
```

### page 10 Graph
```{python, echo=TRUE}
    
plt.plot(results[100000:100020],marker='o')
plt.xlabel('Index')
plt.ylabel('results[100000:100020]')
plt.xticks([5,10,15,20])
plt.show()
```