---
title: "F1 Python ver"
author: "Lee SungHo"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
py_install("matplotlib")
py_install("pandas")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage
## page 9 Preparation
```{python, echo=TRUE}
import numpy as np
import pandas as pd

states=np.arange(0,80,10).astype('str')
P_normal=pd.DataFrame(np.matrix([[0,1,0,0,0,0,0,0],
                    [0,0,1,0,0,0,0,0],
                    [0,0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,0,1],
                    [0,0,0,0,0,0,0,1]]), index=states,columns=states)

P_speed=pd.DataFrame(np.matrix([[.1,0,.9,0,0,0,0,0],
                   [.1,0,0,.9,0,0,0,0],
                   [0,.1,0,0,.9,0,0,0],
                   [0,0,.1,0,0,.9,0,0],
                   [0,0,0,.1,0,0,.9,0],
                   [0,0,0,0,.1,0,0,.9],
                   [0,0,0,0,0,.1,0,.9],
                   [0,0,0,0,0,0,0,1]]), index=states, columns=states)

R_s_a=pd.DataFrame(np.matrix([-1,-1,-1,-1,0.0,-1,-1,0,-1.5,-1.5,-1.5,-1.5,-0.5,-1.5,-1.5,0]).reshape(len(states),2,order='F'),columns=['n','s'],index=states)
print(R_s_a.T)

pi_speed=pd.DataFrame(np.c_[np.repeat(0,len(states)),np.repeat(1,len(states))], index=states, columns=['n','s'])

pi_50=pd.DataFrame(np.c_[np.repeat(0.5,len(states)), np.repeat(0.5,len(states))],index=states, columns=['n','s'])

print(pi_speed.T)
print(pi_50.T)
```



\newpage
## page 11 simulator pi speed
```{python, echo=TRUE}

pi=pi_speed
np.random.seed(1234)
history=[]
MC_N=10000

for MC_i in range(MC_N):
    s_now='0'
    history_i=list(s_now)
    
    while s_now != '70' :
        if np.random.uniform(0,1) < pi.loc[s_now]['n']:
            a_now='n'
            P=P_normal
        else:
            a_now='s'
            P=P_speed
            
        r_now=str(R_s_a.loc[s_now][a_now])
        s_next=states[np.argmin(np.cumsum(P.loc[s_now,]) < np.random.uniform(0,1))]
        history_i.extend([a_now,r_now,s_next])
        s_now=s_next
        
    history.append(history_i)
    
history_speed=history
func=np.vectorize(lambda x: ','.join(x))
pd.Series(func(history_speed[:20]))

```




\newpage
## page 13 simulator pi 50
```{python, echo=TRUE}

pi=pi_50
np.random.seed(1234)
history=[]
MC_N=10000

for MC_i in range(MC_N):
    s_now='0'
    history_i=list(s_now)
    
    while s_now != '70' :
        if np.random.uniform(0,1) < pi.loc[s_now]['n']:
            a_now='n'
            P=P_normal
        else:
            a_now='s'
            P=P_speed
            
        r_now=str(R_s_a.loc[s_now][a_now])
        s_next=states[np.argmin(P.loc[s_now].cumsum() < np.random.uniform(0,1))].item()
        history_i.extend([a_now,r_now,s_next])
        s_now=s_next
        
    history.append(history_i)
    
history_50=history
func=np.vectorize(lambda x: ','.join(x))
pd.Series(func(history_50[:20]))
```

\newpage
## page 17 Implementation 1 $\pi^{speed}$ (vectorized)
```{python, echo=TRUE}
pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','sum'])
print(pol_eval.T)

for MC_i in range(MC_N):
    history_i=history_speed[MC_i]
    
    for j in range(0,len(history_i),3):
        pol_eval.loc[history_i[j]]['count']+=1
        
        if j < len(history_i) :
            pol_eval.loc[history_i[j]]['sum']+=pd.Series(history_i)[range(j+2,len(history_i)-1,3)].astype('float').sum()
            
        else:
            pol_eval.loc[history_i[j]]['sum']+=0

print(pol_eval.T)

pol_cal=pd.DataFrame(pol_eval['sum']/pol_eval['count'])
print(pol_cal.T)
```

\newpage
## page 19 Implementation 2 $\pi^{speed}$ (running estimate)
```{python, echo=TRUE}
pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','est'])
print(pol_eval.T)

for MC_i in range(MC_N):
    history_i=history_speed[MC_i]
    
    for j in range(0,len(history_i),3):
        # update count
        pol_eval.loc[history_i[j]]['count']+=1
        current_cnt=pol_eval.loc[history_i[j]]['count']
        
        # return is the new info
        if j < len(history_i):
            new_info=pd.Series(history_i)[range(j+2,len(history_i)-1,3)].astype('float').sum()
            
        else:
            new_info=0
        
        # update the last estimate with new info    
        alpha=1/current_cnt
        pol_eval.loc[history_i[j]]['est']+=alpha*(new_info-pol_eval.loc[history_i[j]]['est'])
        
        
print(pol_eval.T)
```
\newpage
## page 21 Implementation 3 $\pi^{50}$ (vectorized)

```{python, echo=T}
pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','sum'])
pol_eval.T
for MC_i in range(MC_N):
    history_i=history_50[MC_i]
    
    for j in range(0,len(history_i),3):
        pol_eval.loc[history_i[j]]['count']+=1
        
        if j < len(history_i) :
            pol_eval.loc[history_i[j]]['sum']+=pd.Series(history_i)[range(j+2,len(history_i)-1,3)].astype('float').sum()
            
        else:
            pol_eval.loc[history_i[j]]['sum']+=0
pol_eval.T
pol_cal=pd.DataFrame(pol_eval['sum']/pol_eval['count'])
print(pol_cal.T)
```

\newpage

## page 23 Implementation 4 $\pi^{50}$ (running estimate)

```{python,echo=T}
pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','est'])
pol_eval.T
for MC_i in range(MC_N):
    history_i=history_50[MC_i]
    
    for j in range(0,len(history_i),3):
        # increment count
        pol_eval.loc[history_i[j]]['count']+=1
        current_cnt=pol_eval.loc[history_i[j]]['count']
        
        # return is the new info
        if j < len(history_i):
            new_info=pd.Series(history_i)[range(j+2,len(history_i)-1,3)].astype('float').sum()
            
        else:
            new_info=0
          
        # update the last estimate with new info    
        alpha=1/current_cnt
        pol_eval.loc[history_i[j]]['est']+=alpha*(new_info-pol_eval.loc[history_i[j]]['est'])
        
        
print(pol_cal.T)
```
\newpage
## page 36 Implementation 5 pi speed
```{python,echo=T}
import pandas as pd
import numpy as np

pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','est'])

print(pol_eval.T)

for episode_i in range(len(history_speed)):
  history_i = history_speed[episode_i]
  
  # update count
  for j in range(0,len(history_i),3):
    pol_eval.loc[history_i[j]]['count'] +=1
    current_cnt =pol_eval.loc[history_i[j]]['count']
    
    #build TD target
    if(j < len(history_i)-3):
      TD_tgt = float(history_i[j+2])+pol_eval.loc[history_i[j+3]]['est']
      
    else:
      TD_tgt = 0
      
    # TD-updating  
    alpha = 1/current_cnt
    
    pol_eval.loc[history_i[j]]['est'] += alpha*(TD_tgt - pol_eval.loc[history_i[j]]['est'])
  
print(pol_eval.T)
```
\newpage
## page 37 Implementation 6 pi 50
```{python,echo=T}

pol_eval=pd.DataFrame(np.matrix(np.zeros((len(states)*2))).reshape(len(states),2), index=states, columns=['count','est'])

print(pol_eval.T)

for episode_i in range(len(history_50)):
  history_i = history_50[episode_i]
  
  # update count
  for j in range(0,len(history_i),3):
    pol_eval.loc[history_i[j]]['count'] +=1
    current_cnt =pol_eval.loc[history_i[j]]['count']
    
    #build TD target
    if(j < len(history_i)-3):
      TD_tgt = float(history_i[j+2])+pol_eval.loc[history_i[j+3]]['est']
      
    else:
      TD_tgt = 0
      
    # TD-updating  
    alpha = 1/current_cnt
    
    pol_eval.loc[history_i[j]]['est'] += alpha*(TD_tgt - pol_eval.loc[history_i[j]]['est'])
  
print(pol_eval.T)
```
