---
title: "E1_손민상"
author: "Son Min Sang"  
date:  "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
     in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
py_install("pandas")
py_install("matplotlib")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage
## page 21
```{python, echo=TRUE}
import numpy as np
import pandas as pd

# 0: For a fixed \pi,
# 0: For all states s,
#      define R^{\pi}(s) using Eq.(1)
R = np.hstack((np.repeat(-1.5, 4), -0.5, np.repeat(-1.5, 2), 0)).reshape(8, 1)
# 0: For all states s,s'
#      define P^{\pi}_{ss'} using Eq.(2)
states = np.arange(0, 80, step=10)
P = np.array ([[.1, 0, .9, 0, 0, 0, 0, 0],
               [.1, 0, 0, .9, 0, 0, 0, 0],
               [0, .1, 0, 0, .9, 0, 0, 0],
               [0, 0, .1, 0, 0, .9, 0, 0],
               [0, 0, 0, .1, 0, 0, .9, 0],
               [0, 0, 0, 0, .1, 0, 0, .9],
               [0, 0, 0, 0, 0, .1, 0, .9],
               [0, 0, 0, 0, 0,  0, 0, 1]])

P=pd.DataFrame(P,columns=states,index=states)
```


```{python, echo=TRUE}
print(P)
```


```{python, echo=TRUE}
print(R)
```


\vspace{10pt}

```{python, echo=TRUE}
# 1: Let epsilon <- 10^{-8}
gamma = 1.0
epsilon = 10**(-8)
# 2: Let v_0 <- zero vector
v_old = np.array(np.repeat(0, 8)).reshape(8,1)
# 3: Let v_1 <- R + \gamma*P*v_0
v_new = R+gamma*np.dot(P, v_old)
# 4: i <- 1
# 5: While ||v_i‐v_{i‐1}|| > epsilon
# 6: v_{i+1} <‐ R + \gamma*P*v_{i}
# 7: i <‐ i+1
# 8: Return v_{i+1}
while np.max(np.abs(v_new-v_old)) > epsilon:
    v_old = v_new
    v_new = R+gamma*np.dot(P, v_old)    
print(v_new.T)
```

\vspace{10pt}

```{python, echo=TRUE}
# R, P are already assigned
gamma = 1.0
epsilon = 10**(-8)
v_old = np.array(np.repeat(0, 8)).reshape(8,1)
v_new = R+gamma*np.dot(P, v_old)
results = np.array(v_old) # to save
results= np.append(results,v_new,axis=0) # to save
while np.max(np.abs(v_new-v_old))>epsilon:  
    v_old=v_new
    v_new=R+gamma*np.dot(P,v_old)
    results= np.append(results,v_new) # to save
```

```{python, echo=TRUE}
import pandas as pd
results = pd.DataFrame(np.array(results).reshape(len(results)//8,8),columns = states)
```

```{python, echo=TRUE}
results.head()
```

```{python, echo=TRUE}
results.tail()
```

\newpage

## page 24

```{python}
import matplotlib.pyplot as plt
for i in range(0,6):
    plt.plot(states, results.iloc[i], marker='o', label=str(i+1))
    
plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('Iteration from 1 to 6')
plt.show()
```

\newpage

```{python}
import matplotlib.pyplot as plt
for i in range(7,12):
    plt.plot(states, results.iloc[i], marker='o', label=str(i+1))

plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('7 to 12')
plt.show()
```


\newpage
```{python}
import matplotlib.pyplot as plt
for i in range(13,18):
    plt.plot(states, results.iloc[i], marker='o', label=str(i+1))
plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('Iteration from 13 to 18')
plt.show()
```