---
title: "F1 Python ver"
author: "Lee SungHo"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(background = '718CBA')
library(reticulate)
py_install("matplotlib")
py_install("pandas")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage
## page 15 Skiier1
```{python, echo=TRUE}
import numpy as np
import pandas as pd

states = np.arange(0,80,10).astype('str')
P_normal = pd.DataFrame(np.matrix([[0,1,0,0,0,0,0,0],
                    [0,0,1,0,0,0,0,0],
                    [0,0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,0,1],
                    [0,0,0,0,0,0,0,1]]), index=states,columns=states)
                    
P_speed = pd.DataFrame(np.matrix([[.1,0,.9,0,0,0,0,0],
                   [.1,0,0,.9,0,0,0,0],
                   [0,.1,0,0,.9,0,0,0],
                   [0,0,.1,0,0,.9,0,0],
                   [0,0,0,.1,0,0,.9,0],
                   [0,0,0,0,.1,0,0,.9],
                   [0,0,0,0,0,.1,0,.9],
                   [0,0,0,0,0,0,0,1]]), index=states, columns=states)
R_s_a = pd.DataFrame(np.matrix([-1,-1,-1,-1,0.0,-1,-1,0,-1.5,-1.5,-1.5,-1.5,-0.5,-1.5,-1.5,0]).reshape(len(states),2,order='F'),columns=['n','s'],index=states)
print(R_s_a.T)
pi_speed = pd.DataFrame(np.c_[np.repeat(0,len(states)),np.repeat(1,len(states))], index=states, columns=['n','s'])
pi_50 = pd.DataFrame(np.c_[np.repeat(0.5,len(states)), np.repeat(0.5,len(states))],index=states, columns=['n','s'])
print(pi_speed.T)
print(pi_50.T)

```

\newpage
## page 16 Skiier2
```{python, echo=TRUE}
pi_speed = pd.DataFrame(np.c_[np.repeat(0,len(states)),np.repeat(1,len(states))],index=states,columns=['n','s'])
print(pi_speed.T)

pi_50 = pd.DataFrame(np.c_[np.repeat(0.5,len(states)),np.repeat(0.5,len(states))],index=states,columns=['n','s'])
print(pi_50.T)
```


\newpage
## page 17 Skiier3
```{python, echo=TRUE}
def simul_path(pi, P_normal, P_speed, R_s_a):
    s_now = '0'
    history_i = [s_now]
    
    while s_now!='70':
    
        if(np.random.uniform(1) < pi.loc[s_now]['n']):
            a_now = 'n'
            P = P_normal
    
        else:
            a_now = 's'
            P = P_speed
            
        r_now = R_s_a.loc[s_now][a_now]
        s_next = states[np.argmin(P.loc[s_now].cumsum()<np.random.uniform(1))].item()
        history_i.extend([a_now,r_now,s_next])
        s_now = s_next
    
    return history_i
    
sample_path = simul_path(pi=pi_speed,P_normal=P_normal,P_speed=P_speed,R_s_a=R_s_a)
print(sample_path)
```


\newpage
## page 18 Skiier4
```{python, echo=TRUE}

def simul_step(pi, s_now, P_normal, P_speed, R_s_a):

    if np.random.uniform(1)<pi.loc[s_now]['n']:
        a_now = 'n'
        P = P_normal

    else:
        a_now = 's'
        P = P_speed

    r_now = R_s_a.loc[s_now][a_now]
    s_next = states[np.argmin(P[s_now].cumsum()<np.random.uniform(1))].item()

    if np.random.uniform(1) < pi.loc[s_next]['n']:
        a_next = 'n'

    else:
        a_next = 's'

    sarsa=[s_now,a_now,r_now,s_next,a_next]
    return sarsa

sample_step = simul_step(pi=pi_speed,s_now='0',P_normal=P_normal,P_speed=P_speed,R_s_a=R_s_a)
print(sample_step)

  
```




\newpage
## page 19 Skiier5
```{python, echo=TRUE}
q_s_a = pd.DataFrame(np.c_[np.repeat(0.0,len(states)),np.repeat(0.0,len(states))],index=states,columns=['n','s'])

def pol_eval_MC(sample_path, q_s_a, alpha):
  
  for j in range(0,len(sample_path)-1,3):
      
      s = sample_path[j]
      a = sample_path[j+1]
      G = sum([sample_path[g] for g in range(j+2, len(sample_path)-1 , 3)])
      q_s_a.loc[s][a] = q_s_a.loc[s][a] + alpha*(G - q_s_a.loc[s][a])

  return q_s_a    
  
  
q_s_a = pol_eval_MC(sample_path = sample_path , q_s_a = q_s_a, alpha = 0.1)
q_s_a

```



\newpage
## page 20 Skiier6
```{python, echo=TRUE}
q_s_a = pd.DataFrame(np.c_[np.repeat(0.0,len(states)),np.repeat(0.0,len(states))],index=states,columns=['n','s'])

def pol_eval_TD(sample_step, q_s_a, alpha):
  
    s = sample_step[0]
    a = sample_step[1]
    r = float(sample_step[2])
    s_next = sample_step[3]
    a_next = sample_step[4]
    
    q_s_a.loc[s][a] = q_s_a.loc[s][a] + alpha * (r + q_s_a.loc[s_next][a_next] - q_s_a.loc[s][a])
    
    return q_s_a    
  
  
q_s_a = pol_eval_TD(sample_step = sample_step , q_s_a = q_s_a, alpha = 0.1)
q_s_a

```



\newpage
## page 21 Skiier7
```{python, echo=TRUE}
def pol_imp(pi, q_s_a, epsilon):
  
  for i in range(len(pi)):
    if (np.random.uniform(1) > epsilon):
        pi.iloc[i] = 0
        pi.iloc[i][np.argmax(q_s_a.iloc[i])]=1
      
      
    else:
      pi.iloc[i] = 1/q_s_a.shape[1]
      
    return pi
    
    
pi = pol_imp(pi = pi_speed, q_s_a = q_s_a, epsilon = 0)    

print(pi.T)
```