---
title: "B2_total"
author: "Son Min Sang"
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```



\newpage
## Implementation (page 4)
```{python, echo=TRUE}
import numpy as np

for X in range(11,16):
    MC_N=10000
    D=np.random.choice(np.arange(11,16),MC_N,replace=True) # random discrete uniform
    
    sales_rev=2*np.minimum(D,X) # vector level minimum
    salvage_rev=0.5*np.maximum(X-D,0) # vector level maximum
    material_cost=1*X
    
    profit=sales_rev+salvage_rev-material_cost
    
    print('X: ',X,' expected profit: ',np.mean(profit))
```

\newpage

\vspace{10pt}
## Continuous distribution - grid search approach (page 5)
```{python}
import numpy as np
import pandas as pd

try_X = np.arange(20,40,step=0.01)
exp_profits=np.array([])
for X in try_X:
    MC_N = 10000
    D=np.random.uniform(20,40,size=MC_N)
    sales_rev= 2*np.minimum(D,X) # vector level minimum
    salvage_rev = 0.5*np.maximum(X-D,0) # vector level minimum
    material_cost = 1 *X
    exp_profit= np.mean(sales_rev + salvage_rev - material_cost)
    exp_profits=np.append(exp_profits,exp_profit)
    
results = pd.DataFrame({'try_X':try_X,'exp_profits':exp_profits})
results
```

\newpage

## Plot (page 6)
```{python, echo=TRUE}
from scipy.interpolate import make_interp_spline, BSpline
import matplotlib.pyplot as plt

plt.plot(try_X,exp_profits,'o', color ='black', ms=1,alpha=0.1)
plt.xlabel("try_x")
plt.ylabel("exp_profits")
plt.title("Plot for Expected Profit")
plt.rc('font', size=25)
x_new = np.linspace(results['try_X'].min(),results['try_X'].max(),300)
spline = make_interp_spline(results['try_X'], results['exp_profits'], k=3) 
power_smooth = spline(x_new)
plt.plot(x_new,power_smooth , color = 'blue')
plt.show()
```

\newpage

## page 8
```{python, echo=TRUE}
idx=np.where(exp_profits==np.max(exp_profits))

print(*try_X[idx]) #this is optimal quantity
print(*exp_profits[idx]) #this is expected optimal profit

```


