---
title: "B1_exercise"
author: "Lee SungHo"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')  
```


## *Exercise 1*

*Assume that D follows the following discrete distribution.*


+------------+---+---+---+---+
|　　$d$　   | 20|25 | 30|35 |
|   $P[D=d]$ |0.1|0.2|0.4|0.3|
+:==========:+:=:+:=:+:=:+:=:+
| $30∧d$     | 20|25 |30 |30 |
+------------+---+---+---+---+
|$(30-d)^{+}$|10 |5  |0  |0  |
+------------+---+---+---+---+
|$24∧d$      |20 |24 |24 |24 |
+------------+---+---+---+---+
|$(24-d)^{+}$|4  |0  |0  |0  |
+------------+---+---+---+---+


Answer the followings.


 + $E[30∧D] = \sum((30∧D)·P(D)) = 20×0.1+25×0.2+30×0.4+30×0.3 = 28$
 
 
 + $E[(30-D)^{+}] = \sum((30-D)^{+}·P(D)) = 10×0.1+5×0.2+0×0.4+0×0.3 = 2$
 
 
 + $E[24∧D] = \sum((24∧D)·P(D)) = 20×0.1+24×0.2+24×0.4+24×0.3 = 23.6$
 
 
 + $E[(24-D)^{+}] = \sum((24-D)^{+}·P(D)) = 4×0.1+0×0.2+0×0.4+0×0.3 = 0.4$
 
 
 
## *Exercise 2*

Find your brother's optimal stock level by the above Theorem 2. Then, find his expected profit using the Remark 1.


**Answer**  


$C_o$=(Material Cost - Salvage Price, overstock cost)=$(1-\frac{1}{2})=\frac{1}{2}$   
$C_u$=(Retail Price - Material Cost, understock cost)=(2-1)=1

$E[Profit]$=E(Sale Rev.)+E(salvage Rev.)-E(material Cost)



Newspapers have discrete properties that can count. 
$\therefore F(y) \ge \frac{c_u}{c_o+c_u}$

\vspace{10pt}

$F(y) \ge \frac{1}{1+0.5} = \frac{2}{3}$  


| $d$    |$11$ |$12$ |$13$ |$14$ |$15$ |
|:------:|:---:|:---:|:---:|:---:|:---:|
|$P(D=d)$|$\frac{1}{5}$|$\frac{1}{5}$|$\frac{1}{5}$|$\frac{1}{5}$|$\frac{1}{5}$|



$F_D(11)=\frac{1}{5}$                                                     $<\frac{2}{3}$

$F_D(12)=\frac{1}{5}+\frac{1}{5}=\frac{2}{5}$                             $<\frac{2}{3}$  

$F_D(13)=\frac{1}{5}+\frac{1}{5}+\frac{1}{5}=\frac{3}{5}$                 $<\frac{2}{3}$  

$F_D(14)=\frac{1}{5}+\frac{1}{5}+\frac{1}{5}+\frac{1}{5}=\frac{4}{5}$     $\ge\frac{2}{3}$  


Thus, $x^{*}$=14 



\vspace{10pt}
\\









To find expected profit

Sale Revenue=$2×(D∧X)$, Salvage Revenue=$0.5×(X-D)^{+}$ 

Material Cost=$X$, $x^{*}=14$ 


  
$E[Profit]$=E(Sale Rev.)+E(salvage Rev.)-E(material Cost)

　　　=$\sum_{D=11}^{15}(2×(D∧X)×P(D))+\sum_{D=11}^{15}(0.5×(D-X)^{+}×P(D))-\sum_{D=11}^{15}(X×P(D))$  



->$E[Profit]=\sum_{D=11}^{15}(2×(D∧14)×P(D))+\sum_{D=11}^{15}(0.5×(D-14)^{+}×P(D))-\sum_{D=11}^{15}(14×P(D))$  

　　　　　=$2×(\sum_{D=11}^{14}(D×P(D))+14×P(15))+0.5×\sum_{D=11}^{14}((14-D)×P(D))-14$  

　　　　　=$2×(\frac{11+12+13+14}{5}+\frac{14}{5})+0.5×(\frac{3+2+1+0}{5})-14$  

　　　　　=$12.2$  



$\therefore E[Profit]$ = 12.2$



## *Exercise 3*


Your brother is now selling milk. The customer demands follow $U(20,40)$ gallons. Retail price is $2 per gallon, materia cost is $1 per gallon, and salvage cost is $0.5 per gallon. Find optimal stock level and expected profit.  

**Answer**  


$D$~$U(20,40)$ 


$f_d(x)=\begin{cases}\frac{1}{20}&20\le x \le 40\\0&otherwise\end{cases}$  

$F_d(x)=\begin{cases}0&20<x\\\frac{x-20}{20}&20\le x \le 40\\1&x>40\end{cases}$  

$F(Y)=\frac{C_u}{C_o+C_u}$  



$C_o$=(Material Cost - Salvage Price)=$(1-\frac{1}{2})=\frac{1}{2}$   
$C_u$=(Retail Price - Material Cost)=(2-1)=1



$F(Y) = \frac{1}{1+1/2}$  

$F(Y) =  \frac{2}{3}$  


$\frac{Y-20}{20}=\frac{2}{3}$  


$\therefore x^{*}=\frac{100}{3}$  





To find expected profit

Sale Revenue=$2×(D∧X)$  , Salvage Revenue=$0.5×(X-D)^{+}$

  

Material Cost=$X$ , $x^{*}=\frac{100}{3}$   
   
$E[Profit]$=E(Sale Rev.)+E(salvage Rev.)-E(material Cost)

　　　　　=$E[2×(D∧X)]+E[0.5×(X-D)^{+}]-E[X]$  




$E[Profit]=\int_{20}^{40}(2×(D∧\frac{100}{3})×\frac{1}{20}) d_D+\int_{20}^{40}(0.5×(\frac{100}{3}-D)^{+}×\frac{1}{20}) d_D-\int_{20}^{40}(\frac{100}{30}×\frac{1}{20}) d_D$  


　　　　　=$\frac{1}{10}×(\int_{20}^{\frac{100}{30}}(D) d_D+\int_{\frac{100}{3}}^{40}(\frac{100}{3})d_D)+\frac{1}{40}×\int_{20}^{\frac{100}{3}}(\frac{100}{3}-D)d_D-\frac{100}{3}$  

　　　　　=$\frac{1}{10}×([\frac{1}{2}D^2]^\frac{100}{3}_{20}+\frac{100}{3}[D]^{40}_{\frac{100}{3}})+\frac{1}{40}×[\frac{100}{3}D-\frac{1}{2}D^2]^\frac{100}{3}_{20}-\frac{100}{3}$  

　　　　　=$\frac{80}{3}$  


$\therefore E[Profit] = \frac{80}{3}$


## *Exercise 4*

Lemonade sells for $18 per gallon but only costs 
$3 per gallon to make. If we run out of lemonade, it will be impossible to get more. On the other hand, leftover lemonade has a value of 
$1. Express the following quantity using sale as X and demand as D.

  + $C_u$
  + $C_o$
  + Expected economic cost
  + Expected Profit
  

**Answer**  



$C_u$=(Retail Price - Material Cost)=(18-3)=15

$C_o$=(Material Cost - Salvage Price)=(3-1)=2  





Expected Economic Cost =  E[Cost associated with understock Risk]  + E[Cost associated with overstock Risk]


　　　　　　　　　　　 = $argmin(C_u×E[(D-X)^{+}]+C_o×E[(X-D)^{+}])$  

　　　　　　　　　　　 = $argmin(15×E[(D-X)^{+}]+2×E[(X-D)^{+}])$

\vspace{15pt}

Expected Profit = E[Revenue] - E[Cost]  

　　　　　　　　= $argmax(18×E[(X∧D)]+1×E[(D-X)^{+}]-(3×E[X]+15×E[(D-X)^{+}]+2×E[(X-D)^{+}]))$  

\vspace{20pt}
   
Thus,

  + $C_u=15$
  + $C_o=2$
  + $E[cost]=argmin(15×E[(D-X)^{+}]+2×E[(X-D)^{+}])$
  + $E[profit]=argmax(18×E[(X∧D)]+1×E[(D-X)^{+}]-(3×E[X]+15×E[(D-X)^{+}]+2×E[(X-D)^{+}]))$
  

## *Exercise 5*

**Answer**




## *Book Exercise 16*

A company is obligated to provide warranty service for Product A to its customers next year. The warranty demand for the product follows the following distribution.

| $d$    |$100$ |$200$ |$300$ |$400$ |
|:------:|:---:|:---:|:---:|:---:|
|$Pr(D=d)$|$.2$|$.4$|$.3$|$.1$|



The company needs to make one production run to satisfy the warranty
demand for entire next year. Each unit costs $100 to produce; the penalty
cost of a unit is $500. By the end of the year, the salvage value of each
unit is $50.



(a) Suppose that the company has currently 0 units. What is the optimal
quantity to produce in order to minimize the expected total cost?
Find the optimal expected total cost.



(b) Suppose that the company has currently 100 units at no cost and
there is $20000 fixed cost to start the production run. What is the
optimal quantity to produce in order to minimize the expected total
cost? Find the optimal expected total cost.



a
$C_o$=(Material Cost + Salvage cost, overstock cost)=(100+50)=150   
$C_u$=(penalty cost + Material Cost, understock cost)=(500+100)=600

Unit have discrete properties that can count. 
$\therefore F(y) \ge \frac{c_u}{c_o+c_u}$

$F(y) \ge \frac{600}{150+600} = 0.8$  


From problem's table,

$F_D(100)=0.2$                                                     $<0.8$

$F_D(200)=0.2+0.4$                                                 $<0.8$  

$F_D(300)=0.2+0.4+0.3$                                             $\ge0.8$


Thus, $x^{*}$=300


Expected Economic Cost =  E[Cost associated with understock Risk]  + E[Cost associated with overstock Risk]


= $E[cost]=argmin(600×E[(D-X)^{+}]+150×E[(X-D)^{+}]) = argmin(\sum_{D=100}^{400}(600×(D∧300)×P(D))+\sum_{D=100}^{400}(150×(D-300)^{+}×P(D)))$


=$600×(0.2×100 + 0.4×200 + 0.3×300 +0.1×300)+150×(0.2×200 + 0.4×100 + 0.3×0)  = 126,000$




$\therefore$ Expected Economic Cost = 126,000$


b
$C_o$=(Material Cost + Salvage cost, overstock cost)=(100+50)=150   
$C_u$=(penalty cost + Material Cost, understock cost)=(500+100)=600

Unit have discrete properties that can count. 
$\therefore F(y) \ge \frac{c_u}{c_o+c_u}$

$F(y) \ge \frac{600}{150+600} = 0.8$  


From problem's table,

$F_D(100)=0.2$                                                     $<0.8$

$F_D(200)=0.2+0.4$                                                 $<0.8$  

$F_D(300)=0.2+0.4+0.3$                                             $\ge0.8$


Thus, $x^{*}$=300


Expected Economic Cost =  E[Cost associated with understock Risk]  + E[Cost associated with overstock Risk] + E[Fixed cost]


= $E[cost]=argmin(600×E[(D-X)^{+}]+150×E[(X-D)^{+}]+20000×(D-100)∨1)$