---
title: "C1 Python Code"  
author: "Kang, Eui Hyeon"  
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

```{python import, echo=FALSE,message=F}
import numpy as np
```

\vspace{30pt}

## DTMC Simulator (25p)

```{python, echo=T}
# 25P
def soda_simul(this_state):
    u=np.random.uniform(0,1,size=1)
    
    if this_state=='c':
        if u<=0.7:
            next_state='c'
        else:
            next_state='p'
    else:
        if u<=0.5:
            next_state='c'
        else:
            next_state='p'
            
    return next_state


for i in range(1,6):
    path='c' # 'c'  coke today (day-0)
    
    for n in range(1,10):
        this_state=path[-1] # last elemen
        next_state=soda_simul(this_state)
        path+=next_state
        
    print(path)
```

\newpage

## DTMC Simulator (26p)

```{python, echo=T}
# 26p
def cost_eval(path):
    cost_one_path=path.count('c')*1.5+path.count('p')*1
    
    return cost_one_path

MC_N=10000
spending_records=np.zeros((MC_N,))

for i in range(MC_N):
    path='c'
    for t in range(1,10):
        this_state=path[-1]
        next_state=soda_simul(this_state)
        path+=next_state
        
    spending_records[i]=cost_eval(path)

np.mean(spending_records)
```
