---
title: "A6 Python Code"  
author: "Kang, Eui Hyeon"  
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage

## Data Preparation

```{python}

import pandas as pd
import numpy as np

diamonds=pd.read_csv('./diamonds.csv)
diamonds.head()
```

```{python}

diamonds=diamonds[(diamonds['color']=='G') & (diamonds['carat']<1.75)][['carat','cut','price']].reset_index(drop=True)

diamonds['cut'].unique()
```

```{python}

diamonds.head()
```

```{python}

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

plt.figure(figsize=(12,10))
sns.lmplot(data=diamonds, x='carat', y='price',
           hue='cut', hue_order=['Fair','Good','Very Good','Premium','Ideal'], 
           palette='gist_earth',lowess=True, scatter=False,legend=True)
sns.scatterplot(data=diamonds, x='carat', y='price', hue='cut', hue_order=['Fair','Good','Very Good','Premium','Ideal'],
               palette='gist_earth', s=100, alpha=0.2, legend= False)
plt.grid(True)
plt.xlabel('carat', fontsize=15)
plt.ylabel('price', fontsize=15)
plt.xticks([0.5, 1.0, 1.5])
plt.yticks([0,5000,10000,15000])
plt.show()
```

```{python}

diamonds=pd.get_dummies(diamonds)
diamonds=diamonds.rename(columns={'cut_Very Good':'cut_VeryGood'})
diamonds.head()
```

```{python}

import statsmodels.api as sm

X=diamonds.drop(['price','cut_Ideal'], axis=1)
y=diamonds['price']

X=sm.add_constant(X)
lm_fit=sm.OLS(y,X).fit()
lm_fit.summary()
```

```{python}

pred=lm_fit.predict(X)

plt.figure(figsize=(12,10))
sns.scatterplot(pred, y, s=100, alpha=0.6)
plt.plot([pred.min(),20000],[pred.min(),20000],'k-')
plt.grid(True)
plt.xticks([0,5000,10000,15000,20000])
plt.yticks([0,5000,10000,15000,20000])
plt.xlabel('pred')
plt.ylabel('actual')
plt.show()
```

```{python}

X=diamonds.drop(['price','cut_Ideal'], axis=1)
y_log=np.log(diamonds['price'])

X=sm.add_constant(X)
lm_fit_log=sm.OLS(y_log, X).fit()
print('R square : {0:.4f}'.format(lm_fit_log.rsquared))
```

```{python}

log_pred=lm_fit_log.predict(X)

plt.figure(figsize=(12,10))
sns.scatterplot(log_pred, y_log, s=100, alpha=0.6)
plt.plot([5,log_pred.max()],[5,log_pred.max()],'k-')
plt.grid(True)
plt.xticks([5,6,7,8,9,10])
plt.yticks([5,6,7,8,9,10])
plt.xlabel('pred')
plt.ylabel('actual')
plt.show()
```

\newpage

## 1. Construct a network

```{python}

X=diamonds.drop(['cut_Ideal','price'], axis=1).values
Y_actual=diamonds['price'].values

print('X shape : ',X.shape)
print('Y shape : ',Y_actual.shape)
```

```{python}

from keras import models
from keras import layers

dense_fit=models.Sequential()
dense_fit.add(layers.Dense(units=16, activation='relu', input_shape=(X.shape[1],)))
dense_fit.add(layers.Dense(units=16, activation='relu'))
dense_fit.add(layers.Dense(units=1))
dense_fit.summary()
```

\newpage

## 2. Compile and Fit

```{python}

dense_fit.compile(loss='mse',
                optimizer='adam')
history=dense_fit.fit(X, Y_actual, epochs=30, batch_size=16)
```

```{python}

loss=history.history['loss']
epoch_count=np.arange(1,31)

plt.plot(epoch_count,loss,marker='o')
plt.xlabel('epochs')
plt.ylabel('loss')
plt.show()
```

\newpage

## 3. Predict

```{python}

Y_pred=dense_fit.predict(X).reshape(-1)

results=pd.DataFrame({'Y_pred':Y_pred, 'price':Y_actual})
results.head()
```

```{python}

r_squared=results.corr()**2
r_squared
```

```{python}

plt.figure(figsize=(12,10))

sns.lmplot(data=results, x='Y_pred', y='price',scatter_kws={'alpha':0.1, 'color':'black'})
plt.xlabel('Y_pred', fontsize=15)
plt.ylabel('Y_actual', fontsize=15)
plt.show()
```
