---
title: "C2_Exercises"  
author: "Kwon do yun"  
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: false   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)

```


## Method 1 - eigen-decomposition (p. 12)

```{python}
import numpy as np

P = np.matrix([[0.7,0.3],
              [0.5,0.5]])
              
values , vectors = np.linalg.eig(P.T)

print(values)
print(vectors)

x_1 = vectors[:,0]
v = x_1/sum(x_1)
print("The stationary distribution")
print(v)
```

## p. 15

```{python}
import numpy as np
P = np.matrix([[0.7,0.3],
              [0.5,0.5]])
n = np.size(P,0)
I = np.eye(n)
A = np.c_[P-I,np.repeat(1,n)]
b = np.append(np.repeat(0,n),np.array([1]))

print(A)
print(b)

v = np.dot(np.linalg.inv(np.dot(A,A.T)),np.dot(A,b.T).T)

print(v)

```

## Motivation (p. 17)

```{python}

P = np.matrix([[0.7,0.3],
              [0.5,0.5]])
```

```{python}
np.dot(P,P) #matrix multiplication
```

```{python}
P**3
```

```{python}
P**4
```

```{python}
P**20
```

## p. 19

```{python}
P = np.matrix([[0,1],[1,0]])
```

```{python}
P**2
```
```{python}
P**3
```



```{r, results='hide'}
"Man can learn nothing unless he proceeds from the known to the unknown. - Claude Bernard"
```