---
title: "Lecture C2. Discrete Time Markov Chain2"  
author: "Bong Seok Kim"  
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')  
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(reticulate)
#matplotlib <- import("matplotlib")
#matplotlib$use("Agg", force = TRUE)
```

## Method 1 -eigen-decomposition p.12

```{python, echo=TRUE}
import numpy as np

P=np.array([[0.7, 0.3],[0.5, 0.5]])
print(P)
```

```{python, echo=TRUE}

egien_value, egien_vector = np.linalg.eig(P.T) ## np.linalg,eig(P.T) returns egien_value, egienvector for P^t

print("egien_value :\n",egien_value)

print("egien_vector :\n",egien_vector)

```


```{python, echo=TRUE}

x_1=egien_vector[:,0]

print(x_1)

```

```{python, echo,TRUE}

v=x_1/np.sum(x_1)

print(v)

```

\newpage

## Method2- system of linear equation p.15

```{python, echo=TRUE}
import numpy as np

P=np.array([[0.7, 0.3],[0.5, 0.5]])

n=len(P)

I=np.identity(n)

A=np.c_[P-I,np.repeat(1,n)] # np.c_ == cbind in r

b=np.append(np.repeat(0,n), np.array(1))

print(A)
```


```{python, echo=TRUE}
print(b)
```


```{python, echo=TRUE}
v=np.linalg.solve(np.dot(A,A.T),np.dot(A,b.T))
print(v)
```

\newpage

## Limiting Probability p.17

```{python,echo=TRUE}
from numpy.linalg import matrix_power # provides matrix pwoer

P=np.array([[0.7, 0.3],[0.5, 0.5]])
print(P)
```


```{python,echo=TRUE}
print(np.dot(P,P)) # matrix multiplication
```


```{python,echo=TRUE}
print(matrix_power(P,3))
```


```{python,echo=TRUE}
print(matrix_power(P,4))
```


```{python,echo=TRUE}
print(matrix_power(P,20))
```

\newpage

## The limiting distribution may or may not exit. For example p.19


```{python,echo=TRUE}
from numpy.linalg import matrix_power

P=np.array([[0,1],[1,0]])
print(P)

```


```{python,echo=TRUE}
print(matrix_power(P,2))
```



```{python,echo=TRUE}
print(matrix_power(P,3))
```





```{r message=FALSE, warning=FALSE, paged.print=TRUE}
"Done, Lecture C2. Discrete Time Markov Chain2 "
```