---
title: "E3_손민상"
author: "Son Min Sang"
date: "`r Sys.Date()`"  
output:   
  pdf_document:  
    latex_engine: xelatex
    highlight: haddock  
    keep_tex: true  
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    # pandoc_args: [
    #  "-V", "classoption=twocolumn"
    # ]
    toc: true   
    toc_depth: 2  
    # number_sections: true  
monofont: Consolas
smaller: yes
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(background = '718CBA')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```

\newpage

## page 7

```{python,echo=TRUE}
import numpy as np
import pandas as pd

gamma=1
states=np.arange(0,80,10).astype('str')

P_normal=pd.DataFrame(np.matrix([[0,1,0,0,0,0,0,0],
                    [0,0,1,0,0,0,0,0],
                    [0,0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,0,1],
                    [0,0,0,0,0,0,0,1]]), index=states,columns=states)

P_speed=pd.DataFrame(np.matrix([[.1,0,.9,0,0,0,0,0],
                   [.1,0,0,.9,0,0,0,0],
                   [0,.1,0,0,.9,0,0,0],
                   [0,0,.1,0,0,.9,0,0],
                   [0,0,0,.1,0,0,.9,0],
                   [0,0,0,0,.1,0,0,.9],
                   [0,0,0,0,0,.1,0,.9],
                   [0,0,0,0,0,0,0,1]]), index=states, columns=states)
```

```{python,echo=TRUE}
import numpy as np
import pandas as pd

R_s_a=pd.DataFrame(np.matrix([-1,-1,-1,-1,0.0,-1,-1,0,-1.5,-1.5,-1.5,-1.5,-0.5,-1.5,-1.5,0]).reshape(len(states),2,order='F'),columns=['normal','speed'],index=states)
```

\newpage

## page 8

```{python,echo=TRUE}
import numpy as np
import pandas as pd

# 1. Initialize V
V_old=pd.DataFrame(np.repeat(0,len(states)).reshape(len(states),1),index=states)
V_old.T
```

```{python,ecHo=TRUE}
import numpy as np
import pandas as pd

# 2. Evaluate the Q-function
q_s_a=R_s_a+np.c_[np.dot(gamma*P_normal,V_old),np.dot(gamma*P_speed,V_old)]
q_s_a
```

```{python,echo=TRUE}
import numpy as np
import pandas as pd

# 3. Find the best action for each state
V_new=np.array(q_s_a.apply(max,axis=1)).reshape(len(states),1)
V_new.T
```

\newpage

## page 11

```{python,echo=TRUE}
import numpy as np
import pandas as pd

# Assigned are gamma, states, P_normal, P_speed, R_s_a
cnt=0
epsilon=10**(-8)
V_old=pd.DataFrame(np.repeat(0,len(states)).reshape(len(states),1),index=states)
results=V_old.T # to save
while True:
    q_s_a=R_s_a+np.c_[np.dot(gamma*P_normal,V_old),np.dot(gamma*P_speed,V_old)]
    V_new=np.array(q_s_a.apply(max,axis=1)).reshape(len(states),1)
    
    if np.max(np.abs(V_new-V_old)).item() < epsilon :
        break
    results=np.r_[results, V_new.T]
    V_old=V_new
    cnt+=1
```    

```{python,echo=TRUE}
import pandas as pd

value_iter_process=results
results=pd.DataFrame(results, columns=states)
results.head()
results.tail()
```

\newpage

## page 14
```{python,echo=TRUE}
import matplotlib.pyplot as plt

for i in range(6):
    plt.plot(results.columns,results.iloc[i], label=i,marker='o')
    
plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('Iteration from 1 to 6')
plt.yticks([0,-1,-2,-3,-4])
plt.show()
```

\newpage

```{python,echo=TRUE}
import matplotlib.pyplot as plt

for i in range(7,13):
    plt.plot(results.columns,results.iloc[i], label=i,marker='o')
    
plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('Iteration from 7 to 12')
plt.yticks([0,-1,-2,-3,-4])
plt.show()
```


\newpage

```{python,echo=TRUE}
import matplotlib.pyplot as plt

for i in range(13,19):
    plt.plot(results.columns,results.iloc[i], label=i,marker='o')
    
plt.grid(True)
plt.legend(title='factor(idx)')
plt.xlabel('state')
plt.ylabel('value_fn')
plt.title('Iteration from 13 to 18')
plt.yticks([0,-1,-2,-3,-4])
plt.show()
```

\newpage
## page 18
```{python,echo=TRUE}
V_opt=results.tail(1).T # value_iter_process
V_opt.T
```

```{python,echo=TRUE}
import numpy as np

q_s_a=R_s_a+np.c_[np.dot(gamma*P_normal,V_opt), np.dot(gamma*P_speed, V_opt)]
q_s_a
```

```{python,echo=TRUE}
import numpy as np
import pandas as pd

pi_opt_vec=q_s_a.idxmax(axis=1)
pi_opt_vec
```

```{python,echo=TRUE}
pi_opt=pd.DataFrame(np.zeros((len(states),2)), index=states, columns=['normal','speed'])
for i in range(len(pi_opt_vec)):
    pi_opt.iloc[i][pi_opt_vec.iloc[i]]=1
    
pi_opt.T
```