---
title: "C2 python ver"
author: "Lee SungHo"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  pdf_document:
    latex_engine: xelatex
    highlight: haddock
    keep_tex: yes
    includes:
      in_header: rmd-pdf-support/latex-topmatter.tex
    toc: yes
    toc_depth: 2
monofont: Consolas
smaller: yes
classoption: a4paper
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(background = '718CBA')  
```

\newpage  

# Newsvendor case




## Problem_1


The A/F ratio is the ratio of actual demand divided by the predicted value. As a result of O'Neill's forecast of 3.2 million swimwear sales in 20, the sales data were normally distributed, with the expected A/F ratio of 0.9976 and the standard deviation of the A/F ratio of 0.369. Given that 21 years of swimwear sales are 2.2 million and the A/F ratios are the same, and sales volume is normally distributed, obtain the expected actual demand distribution.


#sol_1 


$\mu=Estimated\, A/F \,Ratio × Demand\, forecasting=0.9976×2,200,000=2,194,720$\
$\sigma=Standard\, deviation\, of\, A/F\, ratio × Demand\, forecasting=0.369×2,200,000=811,800$\
$\therefore\, expected\, actual\, demand= N(2194720,811800)$


## Problem_2


The factory costs $110 to produce swimsuits, $180 to sell at the store and $90. Get the best order quantity using the actual demand you've got earlier.(φ(0.76)=0,7764, φ(0.77)=0.7794)



#sol_2 


$C_o$=(Material Cost - Salvage Price)=(110-90)=$20


$C_u$=(Retail Price - Material Cost)=(180-110)=$70


optimal stock = smallest Y that matches F(Y) = $\frac{c_u}{c_o+c_u}$\


$F(z) = \frac{70}{70+20}$\


$F(z) = \frac{7}{9} \fallingdotseq 0.7778$\


Z = (Q- $\mu$ )/ $\sigma$ \
$\rightarrow\, \therefore Best\, order\, quantity\, =   Q = \mu + Z*\sigma$ = 2,194,720+0.77*811,800 = 2,819,806



